spring:
  application:
    name: activityservice
  data: 
    mongodb:
      uri: mongodb://semadish:dZB8UKQ1q1@localhost:27017/fitnessactivity?authSource=admin
      database: fitnessactivity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8082