spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://semadish:dZB8UKQ1q1@localhost:27017/fitnessrecommendation?authSource=admin
      database: fitnessrecommendation

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083