spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path= /api/users/**

        - id: activityservice
          uri: lb://activityservice
          predicates:
            - Path= /api/activities/**

        - id: aiservice
          uri: lb://aiservice
          predicates:
            - Path= /api/recommendations/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/